version: '3.2'

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  mongodb-volume: